setup.py
While we are at it, let's this tool https://github.com/brettcannon/caniusepython3 know about Python versions
btw, thanks a ton for maintaining up to date fork. I just replaced legacy package with this in all my projects :)
=> specify Python versions

registration/models.py
https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_username
=> use get_username() from AbstractBaseUser

registration/backends/default/views.py, registration/backends/simple/views.py
This makes it possible to override the success url without subclassing
the registration view, simply by passing a success_url in from the
URLConf
=> Make success_url an attribute on registration views

registration/locale/el/LC_MESSAGES/django.po
Fixes #30.
I'm not sure if the translations are up to date, so I didn't touch them at all, just this fix.
=> Fix missing newline in el translation.

registration/templates/registration/activation_email.html, registration/templates/registration/activation_email.txt
Fixes #29.
The translations will need updating.
=> Flatten variable use in blocktrans.

MANIFEST.in
I added the templates of the package to manifest.in to be installed using setup.py and added a newline to the end of the file (pep8).
=> include templates

docs/quickstart.rst, registration/models.py, registration/tests/models.py
=> Add optional setting for default email. Update docs.

CHANGELOG, docs/quickstart.rst
=> Document the need for base.html

docs/simple-backend.rst
=> Correct docs around successful registration redirect

docs/upgrade.rst
Reorganize backwards incompatible changes by affected version. Add information about two previously undocumented changes.
=> Reorganize backwards incompatible changes in "upgrade guide".

registration/forms.py
Use `USERNAME_FIELD` attribute to define the `RegistrationForm` meta fields (useful for custom user models)
=> fix issue #27

registration/admin.py, registration/forms.py, registration/tests/forms.py, registration/tests/forms_custom_user.py, registration/users.py, test_app/models.py
Fixes #27. I also fixed the same issue with the `ModelAdmin`.
=> Support custom user models with the RegistrationForm. Add tests.

registration/south_migrations/0001_initial.py
Despite you configure South to look into
registration.south_migrations modules no table will be created
if there is no 0001_initial
=> Added south initial migrations

registration/locale/th/LC_MESSAGES/django.po
Please review this translation.
=> Add Thai translation

docs/forms.rst
=> fix docs re: password mismatch

registration/admin.py, registration/tests/admin_actions.py, test_app/settings.py, test_app/settings_test.py, test_app/urls_default.py, test_app/urls_simple.py
This PR was created to fix #146
=> Pass the request when resend_activation_email() is triggered from the admin

docs/views.rst, registration/backends/default/views.py, registration/views.py
=> Make method signatures consistent for RegistrationView and AcitvationView classes

.travis.yml, Makefile, README.rst, requirements.txt, tasks.py
If you guys want to merge this, we can also add some docs to the `README` to let people know about it.
What do you guys typically do to manage the different versions of python/Django for testing?
=> Add makefile to help developers get started

CHANGELOG, registration/templates/registration/activate.html
=> Add title to active.html

docs/quickstart.rst
adding comment for prob on:
https://github.com/macropin/django-registration/issues/85#issuecomment-133068403
=> updating docs fix#85

registration/models.py, registration/tests/models.py
https://github.com/macropin/django-registration/pull/178 does not seem to be active anymore, finishing the implementation here
=> Django 110 warning

README.rst
=> Remove typo "regisitration".

CHANGELOG
=> Update changelog for 3-step registration feature

LICENSE
Update the LICENSE file for 2017.
=> Update copyright for 2017

setup.py
Reverts macropin/django-registration#246
=> Revert "Remove invalid framework choice"

CHANGELOG
Just starting a changlog for the next release.
=> Start a changelog for the next release.

registration/tests/default_backend.py, registration/tests/simple_backend.py, registration/views.py
If the user is already logged in, why show the registration page?
=> Redirect Logged Users

registration/templates/registration/password_reset_complete.html
=> change login url

docs/forms.rst, registration/forms.py
=> Add outlook.com to the list of free email providers.

README.rst
@timgraham a pre-release to allow testing again Django 2.0 is now live! Let me know if you run into any issues :)
=> Document prerelease

docs/admin-approval-backend.rst, docs/forms.rst, docs/index.rst, docs/quickstart.rst, docs/upgrade.rst
Addresses #99, #170, #212.
@nehri97, @ahammouda3 & @alzearafat let me know if this address the problems you were seeing!
=> Update docs to address outstanding issues

docs/quickstart.rst
=> clarify setup of INSTALLED_APPS

CHANGELOG, docs/quickstart.rst, registration/models.py, registration/tests/models.py
=> Configure from email from Site object

CHANGELOG, docs/default-backend.rst, registration/backends/default/views.py, registration/models.py, registration/tests/models.py
Addresses #240. @delano, went with the change of signature of ``RegistrationProfile.activate_user``. Would love any comments from you and @dicato before merging.
=> Change return signature of Registration_profile.activate_user to return a tuple

CHANGELOG, docs/views.rst, registration/backends/default/views.py, registration/models.py, registration/tests/models.py, registration/views.py
=> Prevent sending activation email if multiple objects present

CHANGELOG, registration/management/commands/cleanupregistration.py, registration/models.py, registration/tests/models.py
Addresses #233. @felixSchl sorry this so long to get around to. let me know if this addresses your issue! @dicato wasn't sure what you had in mind for beefing up the unit tests but if you have any suggestions happy to throw them in
=> Add logging to cleanup method and use profile.activated

CHANGELOG, registration/models.py, registration/tests/models.py
Addresses #274. @davidfdezc or @sergafts would love any comments from you and @dicato before merging.
=> Fix bug with account deletion for admin_approval backend

registration/models.py, registration/templates/registration/password_reset_email.html, registration/tests/admin_actions.py, registration/tests/admin_approval_backend.py, registration/tests/models.py, test_app/templates/base.html
=> Use get_username method instead of accessing username directly

docs/quickstart.rst, test_app/settings.py
Fixes a bug in app ordering for our test app and associated docs
=> Fix test app

CHANGELOG, registration/models.py, registration/tests/models.py
=> Fix cleanupregistration, skip if user.is_active

registration/templates/registration/admin_approve_complete.html, registration/templates/registration/admin_approve_email.html
addresses https://github.com/macropin/django-registration/issues/348
=> document admin approval emails

registration/templates/registration/admin_approve_complete_email.html, registration/templates/registration/admin_approve_complete_email.txt
This caused a trace-back when using the default templates.
=> Changed path reference from 'login' to 'auth_login

docs/quickstart.rst
replaced tuple with list for INSTALLED_APPS example
=> corrected syntax

registration/models.py, requirements.txt, setup.py, test-requirements.txt, tox.ini
Hi,
While I read `registration/models.py` code, I found some refactor point.
Could you reveiw this?
Also add following changes
- Updaet requirements for failing latest pytest
- Add Django 3.1 to tox.ini
- Update setup.py's classifiers
Thank you.
=> Fix refactor little

registration/models.py, registration/tests/forms.py, registration/tests/models.py
=> Removed more Python 2.7 shims.

registration/tests/forms_custom_user.py
I think we're ready for a new release :confetti_ball:
=> Removed Python 2 compatibility imports.

registration/management/commands/cleanupregistration.py, registration/models.py
This code gives more details for cleanupregistration.
Without this, we don't know there is cleaned user or not.
We can only know, command was run or not.
=> Update cleanupregistration output for more understaing

registration/models.py
https://docs.djangoproject.com/en/3.2/releases/3.2/
=> fix https://github.com/macropin/django-registration/issues/413

registration/locale/id/LC_MESSAGES/django.po
Add Bahasa Indonesia (id) translations
=> add id translations

.readthedocs.yaml
https://blog.readthedocs.com/migrate-configuration-v2/
=> add Read the Docs config

registration/management/commands/cleanupregistration.py
Typo in cleanupregistration management command fixed.
=> Typo in cleanupregistration

test-requirements.txt, tox.ini
Properly separate out various python envs in github actions
=> Use tox-gh-actions

docs/views.rst
Also updated the link to the `dev` version.
=> Fix the markup in ResendActivationView doc
