registration/admin.py
'Already' was misspelled in the `activate_users` doc.
=> Updated admin.py for a small typo :smiley:

registration/models.py
Using `django-registration-redux` reveals the following warning:
```
WARNINGS:
registration.RegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```
This pull request simply fixes that issue by replacing the user field with a OneToOneField.
=> Fix warning on using ForeignKey vs OneToOneField

.travis.yml, registration/tests/forms.py
The error message for invalid usernames was [changed in Django 1.8](https://github.com/django/django/blob/1.8/django/contrib/auth/models.py#L390).
=> Run tests against Django 1.8

registration/views.py
Filter user passwords from appearing in error reports from RegistrationView as recommended in django docs [here](https://docs.djangoproject.com/en/1.7/howto/error-reporting/#django.views.decorators.debug.sensitive_post_parameters)
=> Filter user passwords from appearing in error reports

.travis.yml
The `setup.py` file indicates that Python 3.4 is supported. I've added that to the travis builds. Also bumped to the latest Django minor versions.
=> Test against Python 3.4 and latest Django releases

CHANGELOG, docs/quickstart.rst, registration/models.py, registration/tests/models.py
This addresses the issue raised in https://github.com/macropin/django-registration/issues/50.
Essentially, we just need to document the fact that both templates now need to be overridden. Alternatively, users can add a setting to disable the HTML template.
There is no easy way to determine weather or not a user has overridden one template but not another. It might be possible to inspect the paths of the loaded templates, but that seems like a hack.
=> Add setting for REGISTRATION_EMAIL_HTML that defaults to True.

docs/quickstart.rst
This may be obvious to some, but it would help to identify what blocks are needed in the base.html template.
=> mention blocks needed in base template

docs/default-backend.rst, registration/migrations/0002_registrationprofile_activated.py, registration/migrations/0003_migrate_activatedstatus.py, registration/models.py, registration/tests/models.py
Add a boolean field , `activated` and corresponding migration
to `RegistrationProfile`. Use this field when the user tries
to activate their account to distinguish between:
- account activation failure due to non-existant activation key
- account activation failure due to an expired activation key
- account activation failure due to the user trying to activate
more than once
By distinguising between these scenarios, it is possible to
provide the user with better information during account activation.
Specifically, if the user is active and tries to reactivate,
clearly indicate their account is active and able to login.
Update documentation and unit tests to account for additional
model field and activation logic.
Add both a schema and data migration. Data migration checks
if …
=> Distinguish between activation failure and attempted reactivation. Fix #70

setup.cfg
Django (and South) do not support running migrations from eggs since you cannot discover migrations inside an egg. To overcome this, install django-registration-redux an an unzipped package.
For background, see this [south issue](http://south.aeracode.org/ticket/589) and [discussion](https://groups.google.com/forum/#!topic/south-users/Y56DKtTnHT0). This appears to be a common problem in many Django applications.
To test, install django-registation-redux via `python setup.py install` and ensure you can successfully run `python manage.py migrate` on the `test_app`.
=> Do not install a zipped egg. Fix #103

.coveragerc
I've added a [`.coveragerc` configuration file](http://coverage.readthedocs.org/en/latest/config.html) that omits the `migrations` and `south_migrations` folders.  They aren't explicitly covered in tests, and shouldn't be included in code coverage. 
I set the branch coverage measurement to True, but coveralls.io doesn't seem to have that feature, yet.  If you wanted to see branch coverage, it'd have to be done locally.
=> Coverage configuration

docs/upgrade.rst
Explicitly state that current versions of this package are not
compatible with James Bennett's django-registration package - the
existence of backwards-incompatible changes means that it is not
compatible.
=> Disclaim compatibility with django-registration.

.travis.yml
Figured I would start with something small, but necessary.  I am trying to upgrade to Django 1.9, and since the beta is officially over its probably a good idea to feed travis the latest django.  
Builds successfully.  https://travis-ci.org/awbacker/django-registration
=> Use Django 1.9 instead of 1.9b1 in travis

registration/models.py
According to the issue https://github.com/macropin/django-registration/issues/60
3 added variables that take path to templates from settings (ACTIVATION_EMAIL_SUBJECT, ACTIVATION_EMAIL_BODY, ACTIVATION_EMAIL_HTML), or use the default templates from registration folder.
=> Add the ability to specify a path to email templates

registration/management/commands/cleanupregistration.py
Solve the warning RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
=> Fix deprecated class NoArgsCommand class.

README.rst
I believe it's worth adding alternatives to django-registration in the README. django-registration provides a succinct user registration package, but user registration is only one component of self-servicing user management. As you begin to support other forms of authentication, email as username, two-factor, etc, you are required to customize django-registration extensively. Because of this, I have migrated multiple projects to [django-allauth](http://www.intenct.nl/projects/django-allauth/) with success.
Does anyone have any other alternative packages that should be mentioned?
=> Add alternatives to README.

docs/quickstart.rst
syncdb is deprecated since version 1.7
https://docs.djangoproject.com/en/1.7/ref/django-admin/#syncdb
=> Used migrate instead of syncdb

LICENSE
Update copyright to reflect current authors and maintainers.
Fix #198.
=> Update copyright. Fix #198.

registration/models.py, registration/tests/models.py
I've used Django's `get_random_string` as this uses `random.SystemRandom()`/`os.urandom` and handles the case in which they are not available. You can see the source code here:
https://github.com/django/django/blob/stable/1.8.x/django/utils/crypto.py#L53
As far as I can tell there should be no backwards compatibility issues. I have created a test that should help prove this.
=> Using a cryptographically secure method to generate activation keys

registration/locale/es/LC_MESSAGES/django.po
Adds missing space characters in multi-lines for spanish (es) translation.
=> Fixes multilines in spanish (es) translation.

docs/default-backend.rst, registration/admin.py, registration/backends/default/views.py, registration/models.py, registration/tests/models.py
In Django 1.11 and when not use `Site` framework, following error occured.
```
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```
Use a shortcut.
=> Make Site as optional

registration/migrations/0003_migrate_activatedstatus.py
Fixes: #261
In [RunPython](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython), should specify current connection for testing.
You can see a example in above django docs link.
Because use alias in testing. 
May be same problems are occurred when use multiple databases.
=> Use current database connection's alias for testing. Fixes: #261

CHANGELOG, docs/admin-approval-backend.rst, docs/forms.rst, docs/index.rst, docs/quickstart.rst, docs/signals.rst, registration/models.py, registration/tests/models.py, test_app/settings_test.py
Checks for REGISTRATION_ADMINS defined in settings to use for the
approval email instead of ADMINS. Triggers warning (about using ADMINS)
if setting is not found
=> Add REGISTRATION_ADMINS mail setting for approval

docs/default-backend.rst
The django settings file may dictate where registration.models.RegistrationProfile.send_activation_email gets templates from. These are the email templates that are sent to a user when they sign up in order to activate their account, and to make custom emails the template source must be changed.
=> Add possible settings for activation emails

registration/templates/registration/password_reset_complete.html
Reverts macropin/django-registration#284
PR caused an error identified in #286. According to the Django source code, [`login_url` should be a valid parameter](https://github.com/django/django/blob/5d9b736fd8e09e273fb5aeeca0da268ecea5f1fd/django/contrib/auth/views.py#L328). @cucy what was the original error you were trying to fix? @pgcd thanks for reporting!
=> Revert "change login url"

.travis.yml, requirements.txt
Travis builds non-deterministically fail for python 3.3 due to different versions of the `pytest` library being installed. We now force this package to be `>3.2.1` for builds to pass. 
@ioparaskev this fixes the issue you were going to look at!
=> Fix travis builds

docs/forms.rst
You need to set ``REGISTRATION_FORM`` variable in ``settings.py`` instead of ``REGISTRATION_FORM_PATH``, because in ``registration/views.py`` ``REGISTRATION_FORM_PATH`` is determined using ``REGISTRATION_FORM``:
REGISTRATION_FORM_PATH = getattr(settings, 'REGISTRATION_FORM',
'registration.forms.RegistrationForm')
REGISTRATION_FORM = import_string(REGISTRATION_FORM_PATH)
=> Fixed typo

registration/models.py, registration/tests/default_backend.py, registration/tests/models.py, test_app/settings_test.py
I propose to use `on_commit` for sending out activation emails.
This could be useful when e.g. sending out activation emails are delegated to a celery task. Potential race condition exists, when a user object has yet not been committed to a db while a task broker already attempts to execute email sending. 
A similar problem is described here: https://dev.to/k4ml/django-fixing-race-condition-when-queuing-with-oncommit-hook-7ae
Since `django-registration` relies on Django 1.11+, we could safely use `on_commit` to avoid such situations, as sugested by the post.
The only caveat is that (some) tests would need to use `TransactionTestCase`. 
All the necessary changes are proposed in this PR.
=> Send email on commit

registration/backends/default/views.py, registration/tests/default_backend.py, test-requirements.txt
Default registration form based on django.contrib.auth.forms.UserCreationForm which saves active user to db. This PR prevents it and moves user saving to registration.models.RegistrationManager.create_inactive_user.
It is up to the developer to maintain this behavior in case of a custom registering form. Especially when custom form omit the save method since the default UserModel().objects.create_user implementation also saves user to db.
=> save user and registration profile in one transaction

registration/backends/admin_approval/urls.py
The comment block had instructions for the default backend, but this file is for admin-approval.
=> Make instructions specific to admin-approval

.travis.yml, registration/models.py, registration/tests/forms.py, registration/tests/models.py, tox.ini
Adds a basic no-op wrapper in place of a deprecated decorator from Django 3.0. Updates the `tox` environments to cover Django 3.0 and Python 3.8.
Fixes #371 
This is an alternate approach to that taken in #372
=> Django 3.0 Support

.travis.yml
The current django LTS release (2.2) doesn't support python 3.4. And, python 3.4 is failing here anyways.
=> travis: remove python 3.4 testing

docs/faq.rst
There is a small typo in docs/faq.rst.
Should read `modifying` rather than `modifiying`.
=> docs: Fix simple typo, modifiying -> modifying

registration/admin.py, registration/forms.py, registration/models.py, registration/utils.py
Since Django 3, `ugettext` throws a deprecated warning and is going to be replaced with `gettext`.
https://docs.djangoproject.com/en/3.0/_modules/django/utils/translation/.
=> Deprecate ugettext in favour of gettext

docs/index.rst, docs/quickstart.rst, docs/urls.rst
This patch adds a new page to the documentation highlighting the actual URLs provided by the various `urls.py` files. It also adds documentation for a couple of templates not already present in the documentation.
This patch converts the heading for each template from a bold line to a reStructuredText subsubheading. This makes creating deep links cleaner. If you don't like this change, look at commit `b664aea`.
While most URLs have an associated view and template, some only have one. I've just omitted those sections, but we could explicitly call out those absences.
I'm open to ideas for what to do with the various URLs that reference Django builtin views. We could try to directly hotlink to the Django documentation. These views also come with templates, which I haven't bothered to document …
=> Document default URLs

registration/migrations/0003_migrate_activatedstatus.py
currently django would raise exception if we tried to reverse the migrations because the data migration has no backwards. This avoids that problem [read more](https://django.doctor/advice/C8001)
I found this problem during auditing your codebase. [Read the full report](https://django.doctor/macropin/django-registration)
=>  Allow migrations to be ran backwards

registration/templates/registration/registration_complete.html, registration/tests/default_backend.py, registration/views.py
Show user the e-mail he registered with on the Registration complete page. This can help user to see which e-mail box to check or if he made a mistake in the address.
=> registration complete: show user e-mail he register with

registration/templates/registration/registration_complete.html
The change in #427 never actually worked, because you can't substitute variables inside `{% trans %}`. In fact, for a non-trivial variable like this, one has to use `{% blocktrans with foo=bar %}` to make a simple variable name available inside the translation string.
=> Use blocktrans where we need to substitute a value

registration/apps.py
This seems to have been introduced in #431. The `verbose_name` is used in the admin site to generate the title for the app. The current name seems inappropriate for this purpose.
This PR changes the name back to the original name before #431.
=> Fix verbose name

registration/models.py
Allow the registration profile cleanup to succeed when a user has protected or restricted relations. The cleanup assumes the users that are selected for cleanup have never been activated. But it is possible for an admin to activate a user without using the registration profile. When the user is then deactivated and the profile becomes a valid candidate for cleanup it may have associated records which prevent it from being deleted.
=> Skip deleting users with protected/restricted relations

.github/workflows/ci.yml, .gitignore, docs/release-notes.rst, setup.py, test-requirements.txt, tox.ini
Following the suggestion for third party libraries, support pre-Django4.2 is dropped. https://docs.djangoproject.com/en/5.0/releases/5.0/#third-party-library-support-for-older-version-of-django
=> Test against Django 5.0, drop support Django <4.2
